AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cafe-balu-back
  Sample SAM Template for cafe-balu-back

Globals:
  Function:
    Timeout: 25
    MemorySize: 128

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
  CafeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: CafeApi

  UpdateCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_category/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        UpdateCategory:
          Type: Api
          Properties:
            RestApiId: !Ref CafeApi
            Path: /update_category/{id}/{name}
            Method: put
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_products/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref CafeApi
            Path: /get_products/{status}
            Method: post
  ChangeStatusCategoryOrProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: change_status_category_or_product/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref CafeApi
            Path: /change_status_category_or_product/{status}/{id}/{type}
            Method: patch
  SaveCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: save_category/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref CafeApi
            Path: /save_category/{name}
            Method: post
  CancelSaleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cancel_sales/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref CafeApi
            Path: /cancel_sale/{id}
            Method: patch
  HistorySalesPerDayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: view_sales_history_per_day
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref CafeApi
            Path: /history_per_day/{startDate}/{endDate}
            Method: get

Outputs:
  UpdateCategoryApi:
    Description: "API Gateway endpoint URL for Prod stage for UpdateCategory function"
    Value: !Sub "https://${CafeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_category/{id}/{name}"
  UpdateCategoryFunctionArn:
    Description: "UpdateCategory Lambda Function ARN"
    Value: !GetAtt UpdateCategoryFunction.Arn
  GetProductsApi:
      Description: "API Gateway endpoint URL of Prod stage for GetProducts function"
      Value: !Sub "https://${CafeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_products/{status}"
  GetProductApiFunctionArn:
      Description: "Get Products Lambda Function ARN"
      Value: !GetAtt GetProductsFunction.Arn
  ChangeStatusCategoryOrProductApi:
    Description: "API Gateway endpoint URL of Prod stage for ChangeStatusCategoryOrProduct function"
    Value: !Sub "https://${CafeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/change_status_category_or_product/{status}/{id}/{type}"
  ChangeStatusCategoryOrProductApiFunctionArn:
    Description: "Change Status Category Or Product Lambda Function ARN"
    Value: !GetAtt ChangeStatusCategoryOrProductFunction.Arn
  SaveCategoryApi:
    Description: "Save category API"
    Value: !Sub "https://${CafeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save_category/{name}"
  CancelSaleApi:
    Description: "Cancel sale API"
    Value: !Sub "https://${CafeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cancel_sale/{id}"
  HistoryPerDayApi:
    Description: "View of sales history per day API"
    Value: !Sub "https://${CafeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/history_per_day/{startDate}/{endDate}"
  LambdaExecutionRoleArn:
    Description: "Lambda Execution Role ARN"
    Value: !GetAtt LambdaExecutionRole.Arn