name: Build, Test with Sonar and Deploy to AWS
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: sonarcloud
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Solo despliega en push a la rama main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies for cancel_sales
        run: |
          cd cafe-balu-back/cancel_sales/
          pip install -r requirements.txt

      - name: Install dependencies for change_status_category_or_product/
        run: |
          cd cafe-balu-back/change_status_category_or_product/
          pip install -r requirements.txt

      - name: Install dependencies for get_category
        run: |
          cd cafe-balu-back/get_category/
          pip install -r requirements.txt

      - name: Install dependencies for get products
        run: |
          cd cafe-balu-back/get_products/
          pip install -r requirements.txt

      - name: Install dependencies for save category
        run: |
          cd cafe-balu-back/save_category/
          pip install -r requirements.txt

      - name: Install dependencies for save sale
        run: |
          cd cafe-balu-back/save_sale/
          pip install -r requirements.txt

      - name: Install dependencies for update category
        run: |
          cd cafe-balu-back/update_category/
          pip install -r requirements.txt

      - name: Install dependencies for update product
        run: |
          cd cafe-balu-back/update_product/
          pip install -r requirements.txt

      - name: Install dependencies for history of sales
        run: |
          cd cafe-balu-back/view_sales_history_per_day/
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: sam build -t cafe-balu-back/template.yaml

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name baluchis --capabilities CAPABILITY_IAM --resolve-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2