name: Build and Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Solo despliega en push a la rama main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies for cancel_sales
        run: |
          cd cafe-balu-back/cancel_sales/
          pip install -r requirements.txt

      - name: Install dependencies for change_status_category_or_product
        run: |
          cd cafe-balu-back/change_status_category_or_product/
          pip install -r requirements.txt

      - name: Install dependencies for get_category
        run: |
          cd cafe-balu-back/get_category/
          pip install -r requirements.txt

      - name: Install dependencies for get_products
        run: |
          cd cafe-balu-back/get_products/
          pip install -r requirements.txt

      - name: Install dependencies for save_category
        run: |
          cd cafe-balu-back/save_category/
          pip install -r requirements.txt

      - name: Install dependencies for save_sale
        run: |
          cd cafe-balu-back/save_sale/
          pip install -r requirements.txt

      - name: Install dependencies for update_category
        run: |
          cd cafe-balu-back/update_category/
          pip install -r requirements.txt

      - name: Install dependencies for update_product
        run: |
          cd cafe-balu-back/update_product/
          pip install -r requirements.txt

      - name: Install dependencies for history of sales
        run: |
          cd cafe-balu-back/view_sales_history_per_day/
          pip install -r requirements.txt
      - name: Install dependencies for login
        run: |
          cd cafe-balu-back/login/
          pip install -r requirements.txt
      - name: Install dependencies for new password
        run: |
          cd cafe-balu-back/newPassword/
          pip install -r requirements.txt
      
      - name: Install dependencies for get one product
        run: |
          cd cafe-balu-back/get_one_product/
          pip install -r requirements.txt
      
      - name: Install dependencies for get top sold products
        run: |
          cd cafe-balu-back/top_sold_products/
          pip install -r requirements.txt
      
      - name: Install dependencies for get end of day balance
        run: |
          cd cafe-balu-back/end_of_day_balance/
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: sam build -t cafe-balu-back/template.yaml

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name baluchis --capabilities CAPABILITY_IAM --resolve-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
